services:
  - type: web
    plan: free
    name: govind
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 server.py & python3 -bash start
    repo: https://github.com/GOVIND-BOTS/haramibot      
    branch: master
    envVars:
      - key: SUDO_USERS 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: STRING_SESSION1
        sync: false
      - key: MONGO_URL
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
      - sync: false
      - key: LOG_GROUP_ID
      - sync: false
      - key: START_IMAGE
      - sync: false
      - key: MUSIC_BOT_NAME
      - sync: false
    autoDeploy: false
